#!/bin/sh

# build the py_correlator library and put it in the correct place (CORE_DIRECTORY/lib)
echo "building py_correlator library"

/usr/local/bin/python setup.py install --install-lib=$CORE_DIRECTORY/lib
#python2.5 setup.py install --install-lib=$CORE_DIRECTORY/lib
#python setup.py install --install-lib=/Users/hjhur/Project/correlator-svn/lib

# 8/20/2013 brg:
cp ../lib/*.* .
cp ../lib/*.* ./intel/

# 8/20/2013 brg: py_correlator.so ends up in app/build/lib.macosx-10.6-intel-2.7
cp build/lib.macosx-10.6-intel-2.7/* .
cp build/lib.macosx-10.6-intel-2.7/* ./intel/
