"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, Extension
import os

#from distutils.core import

coreDir = os.environ["CORE_DIRECTORY"]

# 1/30/2014 brg: argv_emulation allows dropping of files onto application bundle to
# launch, which might be nice to have but isn't a priority at the moment.
#OPTIONS = {'argv_emulation': True}

module1 = Extension('py_correlator',
					define_macros = [('CORRELATOR_MACOSX', None)],
                    include_dirs = [coreDir + '/include'],
                    libraries = ['core'],
                    library_dirs = [coreDir + '/lib'],
                    sources = ['py_func.cpp'])

setup(
    app=['correlator.py'],
    setup_requires=['py2app'],
    data_files=[],
	options=dict(py2app=dict(
		plist=dict(
			CFBundleIconFile="./icons/corey",
			CFBundleShortVersionString="1.7.a7",
			CFBundleVersion="1.7 alpha 7"
		))),
    ext_modules=[module1]
)
